name: Pytest + Allure

on:
  push:
    branches: [master, main]
  pull_request:
  workflow_dispatch:      # <- вот это
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # requirements.txt отсутствует, используем явную установку
          pip install pytest allure-pytest allure-python-commons
          sudo apt-get update -y
          sudo apt-get install -y openjdk-17-jre-headless
          sudo apt-get install -y allure

      - name: Run tests with Allure results
        run: |
          pytest --alluredir=allure-results

      - name: Generate Allure report
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload allure-results artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
